credentials:
  usernames:
    Casho:
      email: casho.gomez@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Casimiro Gómez
      username: casho
      password: abc # Will be hashed automatically


    Solana:
      email: rbriggs@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Estructuras Solana
      username: Solana
      password: Solana.2024 # Will be hashed automatically

    David:
      email: ddelarosa@emetalicas.com.mx
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: David de la Rosa
      username: David
      password: David.delarosa.2024 # Will be hashed automatically

    Julio:
      email: csanchez@emetalicas.com.mx
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Julio Sanchez
      username: Julio
      password: Julio.sanchez.2024 # Will be hashed automatically

    Paola:
      email: calidadempsa@emetalicas.com.mx
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Paola Cariño
      username: Paola
      password: Paola.carino.2024 # Will be hashed automatically

    Victor:
      email: vrendon@emetalicas.com.mx
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Victor Rendon
      username: Victor
      password: Victor.rendon.2024 # Will be hashed automatically

    Jonathan:
      email: jehlinger@emetalicas.com.mx
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Jonathan Ehlinger 
      username: Jonathan
      password: Jonathan.ehlinger.2024 # Will be hashed automatically

    Javier:
      email: javier@solana.mx
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Javier Solana 
      username: Javier
      password: Javier.solana.2024 # Will be hashed automatically

    User:
      email: usuarios@test.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Usuario
      username: user
      password: usuarios # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - melsby@gmail.com