cookie:
  expiry_days: 30
  key: some_signature_key # Must be a string
  name: some_cookie_name
credentials:
  usernames:
    Casho:
      email: casho.gomez@gmail.com
      failed_login_attempts: 0
      first_name: Casimiro 
      last_name: Gómez
      logged_in: False
      password: abc
    Solana:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      first_name: Estructuras
      last_name: Solana
      logged_in: False 
      password: Solana.2024 
    # David:
    #   email: ddelarosa@emetalicas.com.mx
    #   failed_login_attempts: 0
    #   first_name: David
    #   last_name: de la Rosa
    #   logged_in: False 
    #   password: David.delarosa.2024
    # Julio:
    #   email: csanchez@emetalicas.com.mx
    #   failed_login_attempts: 0
    #   first_name: Julio
    #   last_name: Sanchez
    #   logged_in: False
    #   password: Julio.sanchez.2024
    # Paola:
    #   email: calidadempsa@emetalicas.com.mx
    #   failed_login_attempts: 0
    #   first_name: Paola
    #   last_name: Cariño
    #   logged_in: False
    #   password: Paola.carino.2024
    # Victor:
    #   email: vrendon@emetalicas.com.mx
    #   failed_login_attempts: 0
    #   first_name: Victor
    #   last_name: Rendon
    #   logged_in: False
    #   password: Victor.rendon.2024
    # Jonathan:
    #   email: jehlinger@emetalicas.com.mx
    #   failed_login_attempts: 0
    #   first_name: Jonathan
    #   last_name: Ehlinger
    #   logged_in: False
    #   password: Jonathan.ehlinger.2024
    # Javier:
    #   email: javier@solana.mx
    #   failed_login_attempts: 0
    #   first_name: Javier
    #   last_name: Solana
    #   logged_in: False
    #   password: Javier.solana.2024
    User:
      email: usuarios@test.com
      failed_login_attempts: 0
      first_name: Usuario
      last_name: Usuario
      logged_in: False
      password: usuarios
