version: '3.7'

services:
    app:
        build: ./
        command: streamlit run app/basico_opencv.py --server.port 8501
        volumes:
            - ./:/usr/src/app
        ports:
            - 8501:8501
        image: zemog/solana:latest